// Auto-generated by scripts/generate-hero-banners.mjs
// Do not edit manually.

export const heroBannerImages = [
  "/images/banner/index_banner1.jpg",
  "/images/banner/index_banner2.jpg",
  "/images/banner/index_banner3.jpg",
  "/images/banner/index_banner4.jpg",
  "/images/banner/index_banner5.jpg",
  "/images/banner/index_banner6.jpg",
] as const;
